name: cpdkylescicluna
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.8+3
  flutter_svg: ^2.0.17
  firebase_core: ^2.0.0
  firebase_database: ^10.0.0
  timezone: ^0.9.2
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/shiba.svg
    - assets/images/petsmart.svg
  uses-material-design: true
  fonts:
    - family: BlackHanSans
      fonts:
        - asset: assets/fonts/BlackHanSans-Regular.ttf
          weight: 700